name: Sleeping Time Reminder
on:
  schedule:
    - cron: '0 23 * * *'   # Runs every day at 11:00 PM UTC
  workflow_dispatch:        # Allows manual run (optional)

jobs:
  remind-sleep:
    runs-on: ubuntu-latest

    steps:
      - name: Print Sleeping Time Message
        run: echo "Ahmad, itâ€™s your sleeping time ðŸ˜´"
